apiVersion: v1
kind: Service
metadata:
  name: shared-manifests
  namespace: default
  labels:
    app: shared-manifests
spec:
  type: ClusterIP
  selector:
    app: shared-manifests
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

